import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { getMembers, getTasks, getTeamStatus, Member, Task, TeamStatus } from "../src/api";
import { colors, radius } from "../src/theme";

const EMPTY_STATUS: TeamStatus = { total: 0, pending_ack: 0, blocked: 0, done: 0 };

export default function Inbox(){
  const {name="Rahul"}=useLocalSearchParams<{name:string}>();
  const [status,setStatus]=useState(EMPTY_STATUS); const[tasks,setTasks]=useState<Task[]>([]); const[members,setMembers]=useState<Member[]>([]);
  const[loading,setLoading]=useState(true); const[error,setError]=useState("");
  const load=useCallback(async()=>{try{setError("");const[s,t,m]=await Promise.all([getTeamStatus(),getTasks(),getMembers()]);setStatus(s);setTasks(t);setMembers(m)}catch{setError("Backend is offline. Start FastAPI on port 8000, then retry.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const active=tasks.filter(t=>!["DONE","CANCELLED"].includes(t.status)); const due=active.filter(t=>t.deadline).length;
  const ownerName=(id:number)=>members.find(m=>m.id===id)?.name??"Unassigned";
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.teal}/>}>
    <View style={s.topline}><View><Text style={s.kicker}>DAILY BRIEF / LIVE</Text><Text style={s.title}>Good morning,{`\n`}{name}.</Text></View><View style={s.live}><View style={s.dot}/><Text style={s.liveText}>SYNCED</Text></View></View>
    {error?<View style={s.error}><Text style={s.errorTitle}>Connection needed</Text><Text style={s.errorText}>{error}</Text><Pressable onPress={load}><Text style={s.retry}>Retry</Text></Pressable></View>:loading?<ActivityIndicator color={colors.teal}/>:<>
      <View style={s.metrics}><Metric value={active.length} label="ACTIVE"/><Metric value={due} label="DEADLINES"/><Metric value={status.blocked} label="RISKS" risk={status.blocked>0}/></View>
      <Text style={s.section}>TEAMOPS SIGNAL</Text><View style={s.signal}><View style={s.rail}/><View style={s.signalBody}><Text style={s.signalTitle}>{status.blocked?`${status.blocked} task${status.blocked>1?"s are":" is"} blocked.`:"Execution path is clear."}</Text><Text style={s.signalText}>{active.length?`${ownerName(active[0].owner_id)} owns ${active[0].title}. ${active.length-1>0?`${active.length-1} more active commitment${active.length-1>1?"s":""}.`:""}`:"No active commitments yet. Create one through TeamOps chat."}</Text></View></View>
      <Text style={s.section}>EXECUTION CHAIN</Text><View style={s.chain}>{active.slice(0,3).map((task,i)=><View key={task.id} style={s.chainRow}><View style={[s.node,task.status==="BLOCKED"&&s.nodeRisk]}><Text style={s.nodeText}>{i+1}</Text></View><View style={s.chainCopy}><Text style={s.chainTask}>{task.title}</Text><Text style={s.chainMeta}>{ownerName(task.owner_id)} · {task.status.replace("_"," ")}</Text></View></View>)}{!active.length&&<Text style={s.empty}>The chain will appear when tasks are assigned.</Text>}</View>
    </>}
    <Pressable style={({pressed})=>[s.button,pressed&&{opacity:.8}]} onPress={()=>router.push({pathname:"/tasks",params:{name}})}><Text style={s.buttonText}>Open today’s task board</Text><Text style={s.arrow}>→</Text></Pressable>
  </ScrollView></SafeAreaView>}

function Metric({value,label,risk=false}:{value:number;label:string;risk?:boolean}){return <View style={[s.metric,risk&&s.metricRisk]}><Text style={[s.metricValue,risk&&{color:colors.amber}]}>{String(value).padStart(2,"0")}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:22,paddingBottom:36},topline:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},kicker:{color:colors.teal,fontSize:11,fontWeight:"900",letterSpacing:1.8},title:{color:colors.ink,fontSize:32,lineHeight:37,fontWeight:"800",letterSpacing:-.8,marginTop:10},live:{flexDirection:"row",alignItems:"center",gap:6,backgroundColor:colors.tealSoft,paddingHorizontal:9,paddingVertical:7,borderRadius:20},dot:{height:6,width:6,borderRadius:3,backgroundColor:colors.teal},liveText:{color:colors.teal,fontSize:9,fontWeight:"900",letterSpacing:1},metrics:{flexDirection:"row",gap:8,marginVertical:28},metric:{flex:1,backgroundColor:colors.panel,padding:14,borderRadius:radius.medium,borderWidth:1,borderColor:colors.line},metricRisk:{backgroundColor:colors.amberSoft},metricValue:{color:colors.ink,fontSize:25,fontWeight:"800"},metricLabel:{color:colors.muted,fontSize:9,fontWeight:"800",letterSpacing:1,marginTop:4},section:{color:colors.muted,fontSize:10,fontWeight:"900",letterSpacing:1.7,marginTop:5,marginBottom:10},signal:{flexDirection:"row",backgroundColor:colors.panel,padding:18,borderRadius:radius.medium},rail:{width:3,borderRadius:2,backgroundColor:colors.teal,marginRight:14},signalBody:{flex:1},signalTitle:{color:colors.ink,fontSize:17,fontWeight:"800"},signalText:{color:colors.muted,lineHeight:21,marginTop:6},chain:{backgroundColor:colors.panel,padding:18,borderRadius:radius.medium,marginBottom:22},chainRow:{flexDirection:"row",alignItems:"center",marginBottom:16},node:{height:30,width:30,borderRadius:15,backgroundColor:colors.tealSoft,borderWidth:1,borderColor:colors.teal,alignItems:"center",justifyContent:"center"},nodeRisk:{backgroundColor:colors.amberSoft,borderColor:colors.amber},nodeText:{color:colors.ink,fontWeight:"900",fontSize:11},chainCopy:{marginLeft:12,flex:1,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:12},chainTask:{color:colors.ink,fontWeight:"700"},chainMeta:{color:colors.muted,fontSize:12,marginTop:4},empty:{color:colors.muted},button:{flexDirection:"row",justifyContent:"space-between",backgroundColor:colors.teal,padding:17,borderRadius:radius.medium},buttonText:{color:colors.canvas,fontWeight:"900"},arrow:{color:colors.canvas,fontWeight:"900",fontSize:18},error:{backgroundColor:colors.amberSoft,padding:18,borderRadius:radius.medium,marginVertical:24},errorTitle:{color:colors.amber,fontWeight:"900",fontSize:16},errorText:{color:colors.ink,marginVertical:8,lineHeight:20},retry:{color:colors.amber,fontWeight:"900"}});
