import { router } from "expo-router";
import { useState } from "react";
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { colors, radius } from "../src/theme";

export default function Login() {
  const [name, setName] = useState("Rahul");
  return <SafeAreaView style={s.page}><View style={s.orbit}><View style={s.dot}/><Text style={s.orbitText}>Execution signal online</Text></View><View style={s.card}><Text style={s.eyebrow}>CASPIAN / TEAMOPS</Text><Text style={s.title}>Turn talk into{`\n`}forward motion.</Text><Text style={s.copy}>Commitments, blockers and dependencies—kept in one shared operational memory.</Text><Text style={s.label}>WHO ARE YOU?</Text><TextInput value={name} onChangeText={setName} placeholder="Your team name" placeholderTextColor={colors.muted} style={s.input}/><Pressable disabled={!name.trim()} style={({pressed})=>[s.button,pressed&&s.pressed,!name.trim()&&s.disabled]} onPress={() => router.replace({ pathname: "/inbox", params: { name:name.trim() } })}><Text style={s.buttonText}>Open my briefing</Text></Pressable></View><Text style={s.foot}>Local-first hackathon build · No production actions</Text></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas,justifyContent:"center",padding:24},orbit:{flexDirection:"row",alignItems:"center",gap:9,marginBottom:18},dot:{height:8,width:8,borderRadius:4,backgroundColor:colors.teal},orbitText:{color:colors.muted,fontSize:12,fontWeight:"700",letterSpacing:1.2,textTransform:"uppercase"},card:{backgroundColor:colors.panel,padding:28,borderRadius:radius.large,borderWidth:1,borderColor:colors.line},eyebrow:{color:colors.teal,fontWeight:"900",letterSpacing:2.2,fontSize:12},title:{color:colors.ink,fontSize:38,lineHeight:43,fontWeight:"800",marginTop:16,letterSpacing:-1.2},copy:{color:colors.muted,fontSize:16,lineHeight:24,marginTop:14,marginBottom:30},label:{color:colors.muted,fontSize:11,fontWeight:"800",letterSpacing:1.5,marginBottom:8},input:{backgroundColor:colors.canvas,color:colors.ink,padding:16,borderRadius:radius.small,marginBottom:12,borderWidth:1,borderColor:colors.line,fontSize:16},button:{backgroundColor:colors.teal,padding:16,borderRadius:radius.small,alignItems:"center"},pressed:{opacity:.82},disabled:{opacity:.45},buttonText:{color:colors.canvas,fontWeight:"900"},foot:{color:colors.muted,textAlign:"center",fontSize:11,marginTop:18}});
