import { useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { getMembers, getTasks, Member, sendChat, setTaskStatus, Task } from "../src/api";
import { colors, radius } from "../src/theme";

export default function Tasks(){
  const{name="Rahul"}=useLocalSearchParams<{name:string}>(); const[tasks,setTasks]=useState<Task[]>([]); const[members,setMembers]=useState<Member[]>([]); const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{setError("");const[t,m]=await Promise.all([getTasks(),getMembers()]);setTasks(t);setMembers(m)}catch{setError("Tasks could not load. Check that the backend is running.")}finally{setLoading(false)}},[]); useEffect(()=>{void load()},[load]);
  const update=async(task:Task,status:string)=>{try{setNotice("");await setTaskStatus(task.id,status);setNotice(`${task.title} marked ${status.replace("_"," ").toLowerCase()}.`);await load()}catch{setError("Task update failed. Try again.")}};
  const assist=async(task:Task,kind:"help"|"snooze")=>{try{const msg=kind==="help"?"Blocked":"Need extension";const result=await sendChat(msg,String(name));setNotice(result.reply||`${task.title}: request sent.`);await load()}catch{setError("TeamOps could not send the request.")}};
  const owner=(id:number)=>members.find(m=>m.id===id)?.name??"Unknown";
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.teal}/>}><Text style={s.kicker}>COMMITMENT BOARD</Text><Text style={s.title}>Today, in order.</Text><Text style={s.subtitle}>Every action updates the shared execution memory.</Text>{notice?<View style={s.notice}><Text style={s.noticeText}>{notice}</Text></View>:null}{error?<Text style={s.error}>{error}</Text>:null}{loading?<ActivityIndicator color={colors.teal}/>:tasks.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Nothing assigned yet</Text><Text style={s.emptyText}>Create a commitment through the API or TeamOps chat, then pull to refresh.</Text></View>:tasks.map((task,index)=><TaskCard key={task.id} task={task} index={index} owner={owner(task.owner_id)} update={update} assist={assist}/>)}</ScrollView></SafeAreaView>}

function TaskCard({task,index,owner,update,assist}:{task:Task;index:number;owner:string;update:(t:Task,s:string)=>void;assist:(t:Task,k:"help"|"snooze")=>void}){const blocked=task.status==="BLOCKED";return <View style={[s.card,blocked&&s.blockedCard]}><View style={s.cardTop}><Text style={s.order}>{String(index+1).padStart(2,"0")}</Text><Text style={[s.badge,blocked&&s.blockedBadge]}>{task.status.replace("_"," ")}</Text></View><Text style={s.task}>{task.title}</Text><View style={s.ownerRow}><Text style={s.owner}>{owner}</Text><Text style={s.deadline}>{task.deadline?`Due ${new Date(task.deadline).toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}`:"No deadline"}</Text></View><View style={s.actions}><Action label="Done" primary onPress={()=>update(task,"DONE")}/><Action label="Blocked" onPress={()=>update(task,"BLOCKED")}/><Action label="Help" onPress={()=>assist(task,"help")}/><Action label="Snooze" onPress={()=>assist(task,"snooze")}/></View></View>}
function Action({label,onPress,primary=false}:{label:string;onPress:()=>void;primary?:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[s.action,primary&&s.actionPrimary,pressed&&{opacity:.68}]}><Text style={[s.actionText,primary&&s.actionTextPrimary]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:22,paddingBottom:40},kicker:{color:colors.teal,fontSize:11,fontWeight:"900",letterSpacing:1.8},title:{color:colors.ink,fontSize:32,fontWeight:"800",letterSpacing:-.8,marginTop:8},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:7,marginBottom:22},notice:{backgroundColor:colors.tealSoft,padding:13,borderRadius:radius.small,marginBottom:12},noticeText:{color:colors.teal,fontWeight:"700"},error:{color:colors.red,marginBottom:12,fontWeight:"700"},card:{backgroundColor:colors.panel,padding:18,borderRadius:radius.large,borderWidth:1,borderColor:colors.line,marginBottom:14},blockedCard:{borderColor:colors.amber},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},order:{color:colors.muted,fontWeight:"900",fontSize:12,letterSpacing:1},badge:{color:colors.teal,backgroundColor:colors.tealSoft,fontSize:9,fontWeight:"900",paddingHorizontal:8,paddingVertical:6,borderRadius:12,overflow:"hidden"},blockedBadge:{color:colors.amber,backgroundColor:colors.amberSoft},task:{color:colors.ink,fontSize:21,fontWeight:"800",marginTop:18},ownerRow:{flexDirection:"row",justifyContent:"space-between",marginTop:10,paddingBottom:17,borderBottomWidth:1,borderBottomColor:colors.line},owner:{color:colors.ink,fontWeight:"700"},deadline:{color:colors.muted},actions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:16},action:{borderWidth:1,borderColor:colors.line,borderRadius:radius.small,paddingHorizontal:14,paddingVertical:10},actionPrimary:{backgroundColor:colors.teal,borderColor:colors.teal},actionText:{color:colors.ink,fontSize:12,fontWeight:"800"},actionTextPrimary:{color:colors.canvas},empty:{backgroundColor:colors.panel,padding:24,borderRadius:radius.large},emptyTitle:{color:colors.ink,fontSize:19,fontWeight:"800"},emptyText:{color:colors.muted,lineHeight:21,marginTop:7}});
